# mysql
mysql:
  host: 192.168.150.101
  port: 3306
  database: libre
  username: root
  password: 123456

# redis
redis:
  host: 192.168.150.101
  port: 6379
  database: 0
  password: 123456

# elasticsearch
es:
  host: 192.168.150.101
  port: 9200
# security
security:
  pepper: 8a77fd7f7ee9b36a965e0c6fc56f3230

# 业务配置
business:
  lend:
    max-lend-count: 3