# tomcat
server:
  port: 8080

# springboot
spring:
  # 激活环境
  profiles:
    active: dev
    group:
      dev:
        - dev-db
        - dev-redis
        - dev-logging
        - dev-security
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 使用旧的匹配方式已兼容Knife4j文档依赖